version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      - POSTGRES_NAME=rub2b_db
      - POSTGRES_USER=rub2badmin
      - POSTGRES_PASSWORD=Gremushka27112007

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/rub2b
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=rub2b_db
      - POSTGRES_USER=rub2badmin
      - POSTGRES_PASSWORD=Gremushka27112007
    depends_on:
      - db