version: '3.7'

services:
  web:
    build:
      context: ./rub2b_dev
      dockerfile: Dockerfile.prod
    command: gunicorn rub2b_server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - rub2b
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - rub2b

volumes:
  postgres_data:

networks:
  rub2b:
    driver: bridge